config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                    Controller#Action
#            root GET    /                              static_pages#home
#           users POST   /users(.:format)               users#create
#        new_user GET    /users/new(.:format)           users#new
#         session POST   /session(.:format)             sessions#create
#     new_session GET    /session/new(.:format)         sessions#new
#                 DELETE /session(.:format)             sessions#destroy
#        pictures GET    /pictures(.:format)            api/recipes#pictures
#       api_users GET    /api/users(.:format)           api/users#index {:format=>:json}
#        api_user GET    /api/users/:id(.:format)       api/users#show {:format=>:json}
#                 PATCH  /api/users/:id(.:format)       api/users#update {:format=>:json}
#                 PUT    /api/users/:id(.:format)       api/users#update {:format=>:json}
#       api_group POST   /api/group(.:format)           api/groups#create {:format=>:json}
#                 GET    /api/group(.:format)           api/groups#show {:format=>:json}
#      api_groups GET    /api/groups(.:format)          api/groups#index {:format=>:json}
# api_user_groups POST   /api/user_groups(.:format)     api/user_groups#create {:format=>:json}
#  api_user_group PATCH  /api/user_groups/:id(.:format) api/user_groups#update {:format=>:json}
#                 PUT    /api/user_groups/:id(.:format) api/user_groups#update {:format=>:json}
#                 DELETE /api/user_groups/:id(.:format) api/user_groups#destroy {:format=>:json}
#     api_recipes GET    /api/recipes(.:format)         api/recipes#index {:format=>:json}
#                 POST   /api/recipes(.:format)         api/recipes#create {:format=>:json}
#      api_recipe GET    /api/recipes/:id(.:format)     api/recipes#show {:format=>:json}
#                 PATCH  /api/recipes/:id(.:format)     api/recipes#update {:format=>:json}
#                 PUT    /api/recipes/:id(.:format)     api/recipes#update {:format=>:json}
#                 DELETE /api/recipes/:id(.:format)     api/recipes#destroy {:format=>:json}
#    api_tab_tags GET    /api/tab_tags(.:format)        api/tab_tags#index {:format=>:json}
#    api_comments GET    /api/comments(.:format)        api/comments#index {:format=>:json}
#                 POST   /api/comments(.:format)        api/comments#create {:format=>:json}
#    api_requests GET    /api/requests(.:format)        api/requests#index {:format=>:json}
#                 POST   /api/requests(.:format)        api/requests#create {:format=>:json}
#

Rails.application.routes.draw do
  root to: "static_pages#home"

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  get "pictures", to: "api/recipes#pictures"
  namespace :api, defaults: {format: :json} do
    resources :users, only: [:show, :index, :update]
    resource :group, only: [:show, :create]
    get "groups", to: "groups#index"
    resources :user_groups, only: [:create, :update, :destroy]
    resources :recipes, only: [:create, :index, :update, :destroy, :show]
    resources :tab_tags, only: [:index]
    resources :comments, only: [:index, :create]
    resources :requests, only: [:index, :create]
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string
#  name            :string           not null
#  image           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email          (email) UNIQUE
#  index_users_on_session_token  (session_token)
#

class User < ActiveRecord::Base
  validates :email, :password_digest, :name, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :requests, dependent: :destroy
  


  def assign_session_token
    self.update(session_token: SecureRandom.urlsafe_base64)
  end

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    if user && user.is_password?(user_params[:password])
      return user
    end
  end

  def logout
    self.update(session_token: nil)
  end

  def self.find_by_token(session_token)
    return if session_token.nil?
    User.find_by_session_token(session_token)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def find_family
    # does nothing until we have families ... and then is the .groups.first association
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :validate_user
  
  def show
    @user = User.find(params[:id])
    render json: @user
  end

  def index
    @users = Users.find_family
    render json: @users
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    p user_params
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="bkg">
<img class="pic col-sm-8 col-sm-offset-2" src="/assets/CookBooks-logo.png"></img>
<div class="well">
<div class="row bkg">
  <div class="col-sm-8 col-sm-offset-2 form">
    <div class="row">
      <form class="form-horizontal" action= "<%= users_url %>" method="post">
      <div class="col-xs-4"></div>
      <div class="col-xs-4">
        <h3>Sign Up</h3>
      </div>
    </div>

    <div class="row">
      <ul class="col-xs-4 col-xs-offset-4">
        <% if flash[:errors] %>
          <% flash[:errors].each do |error|%>
            <li class="errors"><%= error %></li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div class="row">
      <div class="col-xs-2"></div>
      <div class="col-xs-8">
          <input type="hidden" name="authenticity_token" value="<%=auth_token%>">
        <div class="form-group">
          <div class: "col-xs-12">Already a Member?
            <%= link_to "Log In", new_session_url%>
          </div>
        </div>
        <div class="form-group">
          <label for="name">Name</label>
          <input id="name" class="form-control"
            type="text" name="user[name]" value="<%=@user.name%>">
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input id="email" class="form-control"
            type="email" name="user[email]" value="<%=@user.email%>">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input id="password" class="form-control"
            type="password" name="user[password]" value="">
        </div>
        <div class="form-group">
          <input class="col-xs-12 form-control" type="submit">
        </div>
        <div class="form-group">
          <input class="col-xs-12 form-control" id="myBtn" type="submit" value="Log In as Guest">
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
  <script type="text/javascript">
    document.getElementById("myBtn").addEventListener("click", demoLogin)
  </script>